name: Test

on:
  pull_request:
    branches:
      - master
      - test
      - staging
      - release

jobs:
  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  Test:
    name: Test
    needs: [gitleaks]
    runs-on: ubuntu-latest

    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/os-release

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Check Lint
        run: npm run lint

  Notification:
    if: ${{ failure() }}
    needs: [gitleaks, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.OPENLYTIC_MSTEAMS_WEBHOOK }}
          notification-summary: Organization app test failed for ${{ github.event.pull_request.head.ref }} → ${{ github.base_ref }}!
          notification-color: dc3545
          timezone: Asia/Dhaka